name: Flights App

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/flights/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches: [main]
    paths:
      - 'packages/flights/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Yarn & Lerna Setup
        run: |
          yarn
          yarn lerna bootstrap
      - name: Build
        run: yarn lerna run build --scope flights
      - name: Lint
        run: |
          yarn lerna run lint --scope flights
      - name: Test
        run: |
          yarn lerna run test --scope flights

  os-compatibility:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Build
        run: yarn lerna run build --scope flights
      - name: Lint
        run: yarn lerna run lint --scope flights
      - name: Test
        run: yarn lerna run test --scope flights


  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Build
        run: yarn lerna run build --scope flights
      - name: Lint
        run: yarn lerna run lint --scope flights
      - name: Test
        run: yarn lerna run test --scope flights

  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        typescript-version: ['~4.0.0', '~4.1.0', latest, next, beta, rc]
        include:
          - typescript-version: '~4.0.0'
            experimental: false
          - typescript-version: '~4.1.0'
            experimental: false
          - typescript-version: latest
            experimental: false
          - typescript-version: beta
            experimental: false
          - typescript-version: rc
            experimental: true
          - typescript-version: next
            experimental: true


    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run: |
          yarn lerna add -D typescript@${{ matrix.typescript-version}}
      - name: Build
        run: yarn lerna run build --scope flights
      - name: TypeScript compile
        run: |
          yarn replace-in-file 'import chalk' 'import * as chalk' node_modules/gatsby-cli/lib/reporter/reporter.d.ts
          yarn lerna run typecheck --scope flights
      - name: Lint
        run: yarn lerna run lint --scope flights
      - name: Test
        run: yarn lerna run test --scope flights
