name: Website

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/**/*'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches: [main]
    paths:
      - 'packages/**/*'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test website
        run: yarn workspace website run test:jest
      - name: Test chat app
        run: yarn workspace chat run test
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/website
          start: yarn test:cypress
          key: cypress-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          install-command: yarn install
          browser: chrome
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  os-compatibility:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        # - macos-latest
        - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: |
          yarn workspace website run test:jest
          yarn workspace chat run test

  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]
        # node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
          yarn-version: 1.22
      - run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn workspace foreach --from {chat,website} run test:jest
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/website
          start: yarn test:cypress
          key: cypress-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          install-command: yarn install
          browser: chrome
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        typescript-version: [~5.2.0, latest, next, beta, rc]
        include:
          - typescript-version: '~5.2.0'
            experimental: false
            name: 'ts-5.2'
          - typescript-version: latest
            experimental: false
            name: 'ts-stable'
          - typescript-version: beta
            experimental: false
            name: 'ts-beta'
          - typescript-version: rc
            experimental: true
            name: 'ts-rc'
          - typescript-version: next
            experimental: true
            name: 'ts-canary'


    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run:  yarn workspace foreach add -D typescript@${{ matrix.typescript-version}}
      - name: Build
        run: yarn build
      - name: Type-check website 
        run: |
          yarn replace-in-file 'import chalk' 'import * as chalk' node_modules/gatsby-cli/lib/reporter/reporter.d.ts
          yarn workspace website run typecheck
      - name: Test
        run: yarn workspace foreach --from {chat,website} run test:jest
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/website
          start: yarn test:cypress
          key: cypress-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          install-command: yarn install
          browser: chrome
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [build, os-compatibility, node-compatibility, ts-compatibility]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn
      - name: Build
        run: yarn workspace website run build-prod
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./packages/website/public
          cname: www.typescript-training.com

